### ISSUE TITLE
Design Document defining integration

### ISSUE THREAD

**Issue by peterlamar** [CiscoCloud/mantl-api#8]
As a developer, I know how to package my framework so it can be easily deployed so that the extended teams can add frameworks for the API

@cdmitri @stevendborrelli Please add additional info

**Comment by ryane** [comment]
# Mantl API

An API interface to [Mantl](https://mantl.io).

Currently, Mantl API allows you to install and uninstall [DCOS packages](https://github.com/mesosphere/universe) on Mantl. More capabilities are planned for the future.



**Table of Contents**
- [Mantl API](#mantl-api)
  - [Package Repository](#package-repository)
    - [Tree Structure](#tree-structure)
    - [Multiple Repositories](#multiple-repositories)
  - [Packages](#packages)
    - [Structure](#structure)
      - [package.json](#packagejson)
      - [config.json](#configjson)
      - [mantl.json](#mantljson)
      - [marathon.json](#marathonjson)
      - [uninstall.json](#uninstalljson)
  - [API Reference](#api-reference)
    - [Endpoints](#endpoints)
    - [GET /health](#get-health)
    - [GET /1/packages](#get-1packages)
    - [GET /1/packages/<package>](#get-1packagespackage)
    - [POST /1/installs](#post-1installs)
    - [DELETE /1/installs](#delete-1installs)
  - [Comparison to Other Software](#comparison-to-other-software)
  - [Future Enhancement Ideas](#future-enhancement-ideas)
  - [Issues](#issues)



## Package Repository

Mantl API depends on a repository of package definitions stored in the Consul KV store. [mantl-universe](https://github.com/ciscocloud/mantl-universe) is the authoritative repository of packages that work out-of-the-box on Mantl today. You can install any of the [DCOS packages](https://github.com/mesosphere/universe) but you will likely have to customize some of the configuration to work on Mantl. Most of the Mesosphere packages assume that service discovery is provided by [Mesos-DNS](https://github.com/mesosphere/mesos-dns) and need to be converted to work with the [Consul DNS](https://www.consul.io/docs/agent/dns.html) interface.

### Tree Structure

Mantl API is compatible with the [package repository structure](https://github.com/mesosphere/universe/#package-entries) created for Mesosphere DCOS packages. Each repository contains a directory structure that looks something like this:

```
repo/packages
├── C
│   ├── cassandra
│   │   ├── 0
│   │   │   ├── config.json
│   │   │   ├── marathon.json
│   │   │   └── package.json
│   │   ├── 1
│   │   │   ├── command.json
│   │   │   ├── config.json
│   │   │   ├── marathon.json
│   │   │   └── package.json
├── H
│   └── hdfs
│       ├── 0
│       │   ├── command.json
│       │   ├── config.json
│       │   ├── marathon.json
│       │   └── package.json
│       ├── 1
│       │   ├── command.json
│       │   ├── config.json
│       │   ├── marathon.json
│       │   └── package.json
|__ ...
```

For each named package (_cassandra_ and _hdfs_ in the example above), there is a directory of JSON files corresponding to each version.

### Multiple Repositories

Mantl API supports the ability to layer repositories. Mantl API is configured to use two repository sources by default:
- [Mesosphere Universe](https://github.com/mesosphere/universe)
- [Mantl Universe](https://github.com/CiscoCloud/mantl-universe)

The order of the repositories is important. By default, Mesosphere Universe is configured with index 0 and Mantl Universe is configured with index 1. In the Consul KV store, the repositories are stored as follows:

| Name | Consul KV Path |
| --- | --- |
| Mesosphere Universe | mantl-install/repository/0 |
| Mantl Universe | mantl-install/repository/1 |

Repositories with higher indexes are prioritized. When Mantl API receives a request to install a particular package, it will use the package definition found in the repository with the highest index. If there are any required files missing, it will look for the corresponding package version in the repositories with the lower indexes until it is able to construct a valid, installable package. For example, if `mantl-install/repository/1/repo/packages/H/hdfs/1` (Mantl Universe) exists but does not have a `config.json` file, Mantl API will merge in the `config.json` file from `mantl-install/repository/0/repo/packages/H/hdfs/1` (Mesosphere universe). This enables us to use the existing packages in the Mesosphere Universe without having to recreate everything in the Mantl Universe. Packages in the Mantl Universe repository typically just contain only the changes that are needed to run the package on Mantl clusters.

This also enables users to create their own repository to customize packages for their specific needs.

### Configuring Sources

If you want to use different source repositories, you can specify a configuration file that contains your source definitions using the `--config-file` argument. Here is an example configuration file that uses 2 sources &mdash; one named "mesosphere" from a git repository and the other named "mantl-universe" from the local file system:

``` toml
[sources]

[sources.mesosphere]
path = "https://github.com/mesosphere/universe.git"
type = "git"
index = 0

[sources.mantl]
path = "/home/ryan/Projects/mantl-universe"
index = 1
```

The following attributes can be specified for each source:
- path
- type &mdash; git or filesystem (default)
- index
- branch &mdash; only applicable for the _git_ type

### Synchronizing Repository Sources

The package repositories are synchronized to the Consul K/V backend. If you want to refresh your repositories, you can run the following command:

``` shell
mantl-api sync --consul http://consul.service.consul:8500
```

## Packages

The goals of the packaging system are:
1. Make it easy to contribute packages to Mantl
2. Rely on existing DCOS packages when possible
3. Immutable package versions
4. Ability for users to build customized package versions

### Structure

Mantl Universe packages are based on the [DCOS packaging format](https://github.com/mesosphere/universe/#organization) from Mesosphere. Packages in Mantl Universe are intended to be installed with [Mantl API](https://github.com/CiscoCloud/mantl-api/) and may depend on the corresponding package version in the [Mesosphere Universe](https://github.com/mesosphere/universe/).

Each package is made up of several json files:

#### package.json

The [package.json](https://github.com/mesosphere/universe/#packagejson) file is where package metadata is set. This includes things like the name, version, description, and maintainer of the package.

In Mantl Universe, the `package.json` is optional if the intention is to use the `package.json` from the corresponding package version in the [Mesosphere Universe](https://github.com/mesosphere/universe/).

#### config.json

The [config.json](https://github.com/mesosphere/universe/#configjson) file contains the configuration schema and defaults for the package.

In Mantl Universe, the `config.json` is optional if the intention is to use the `config.json` from the corresponding package version in the [Mesosphere Universe](https://github.com/mesosphere/universe/).

#### mantl.json

The `mantl.json` overrides configuration defaults from the `config.json` file (either directly in the package or from the `config.json` for the corresponding package version in the Mesosphere universe) with values that are known to work on Mantl.

Also, the presence of the mantl.json dictates whether the package is "supported" on Mantl. It can be empty `{}` if there is no specific changes required to make the package run on Mantl.

#### marathon.json

The [marathon.json](https://github.com/mesosphere/universe/#marathonjson) file contains the [Marathon application json](https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps) for the package. It is a [mustache](https://mustache.github.io/) template that is rendered using data from `config.json` and `mantl.json`.

In Mantl Universe, the `marathon.json` is optional if the intention is to use the `marathon.json` from the corresponding package version in the [Mesosphere Universe](https://github.com/mesosphere/universe/).

#### uninstall.json

The `uninstall.json` defines additional behavior when uninstalling a package. The uninstall support is currently limited to removing zookeeper nodes. It is also a mustache template so that variables from `config.json` and `mantl.json` can be used in the uninstall definition.

``` json
{
  "zookeeper": {
    "delete": [
      {
        "path": "{{kafka.storage}}",
        "always": true
      }
    ]
  }
}
```

_Example uninstall.json that deletes zookeeper nodes with a path based on the `kafka.storage` variable._

### Developing Packages

When developing packages, it is easiest to run Mantl API locally and point it to a Mantl cluster. Using a Vagrant Mantl cluster is the simplest and fastest as pointing Mantl API to a remote cluster can be complicated by security settings. However, here is an example configuration file (`config.toml`) showing how to run Mantl API locally against a remote Mantl cluster.

``` toml
consul = "https://control-node:8500"
marathon = "https://control-node/marathon"
marathon-user = "user"
marathon-password = "password"
marathon-no-verify-ssl = true
mesos-principal = "mesos-principal"
mesos-secret = "mesos-secret"
mesos = "http://control-node:15050"
mesos-no-verify-ssl = true
zookeeper = "control-node:2181"

# global
log-level = "debug"

[sources]

[sources.mantl]
path = "/Users/ryan/Projects/mantl-universe"
index = 0
```

You will need to update the URLs and credentials as appropriate for your cluster. If you cluster is secured with SSL, you may also need to export the following variable to prevent errors when connecting to Consul:

``` shell
export CONSUL_HTTP_SSL_VERIFY=false
```

Finally, you will need to update firewalls and security groups so that your development machine has access to the above ports.

You can then run Mantl API with a command like the following:

``` shell
./bin/mantl-api --config-file config.toml
```

As shown above, you should have a copy of a valid repository on your local file system. The easiest thing to do is clone or fork [Mantl](https://github.com/CiscoCloud/mantl-universe). Create or update your package in this local repository. When you want to test it, you first need to synchronize it to the Mantl cluster. You can run a command like the following to synchronize the repository:

``` shell
./bin/mantl-api --config-file config.toml sync
```

Then, you should be able to install your package using normal Mantl API calls. For example:

``` shell
curl -X POST -d "{\"name\": \"mycustompackage\"}" http://localhost:4001/api/1/installs
```

## API Reference

### Endpoints

| Endpoint | Method | Description |
| --- | --- | --- |
| `/health` | GET | health check - returns `OK` with an HTTP 200 status |
| `/1/packages` | GET | list available packages |
| `/1/packages/:name` | GET | provides information about a specific package |
| `/1/installs` | POST | install a package |
| `/1/installs` | DELETE | uninstalls a specific package |

**This document uses endpoints from an unreleased version of Mantl API. See https://github.com/CiscoCloud/mantl-api/issues/13.**

### GET /health

`GET /health`: returns `OK`

``` shell
curl http://mantl-control-01/api/health
```

```
OK
```

### GET /1/packages

`GET /1/packages`: returns a JSON representation of packages available to install.

``` shell
curl http://mantl-control-01/api/1/packages | jq .
```

``` json
[
  {
    "name": "cassandra",
    "description": "Apache Cassandra running on Apache Mesos",
    "framework": true,
    "currentVersion": "0.2.0-1",
    "supported": true,
    "tags": [
      "mesosphere",
      "framework",
      "data",
      "database"
    ],
    "versions": {
      "0.1.0-1": {
        "version": "0.1.0-1",
        "index": "0",
        "supported": true
      },
      "0.2.0-1": {
        "version": "0.2.0-1",
        "index": "1",
        "supported": true
      }
    }
  },
  ...
  {
    "name": "swarm",
    "description": "Swarm is a Docker-native clustering system.",
    "framework": true,
    "currentVersion": "0.4.0",
    "supported": false,
    "tags": [
      "mesosphere",
      "framework",
      "docker"
    ],
    "versions": {
      "0.4.0": {
        "version": "0.4.0",
        "index": "0",
        "supported": false
      }
    }
  }
]
```

### GET /1/packages/<package>

`GET /1/packages/<package>`: returns a JSON representation of a package.

``` shell
curl http://mantl-control-01/api/1/packages/cassandra | jq .
```

``` json
{
  "name": "cassandra",
  "description": "Apache Cassandra running on Apache Mesos",
  "framework": true,
  "currentVersion": "0.2.0-1",
  "supported": true,
  "tags": [
    "mesosphere",
    "framework",
    "data",
    "database"
  ],
  "versions": {
    "0.1.0-1": {
      "version": "0.1.0-1",
      "index": "0",
      "supported": true
    },
    "0.2.0-1": {
      "version": "0.2.0-1",
      "index": "1",
      "supported": true
    }
  }
}
```

### POST /1/installs

`POST /1/installs`: post a JSON representation of a package to install.

``` shell
curl -X POST -d "{\"name\": \"cassandra\"}" http://mantl-control-01/api/1/installs | jq .
```

``` json
{
  "id": "/cassandra/dcos-test",
  "cmd": "$(pwd)/jre*/bin/java $JAVA_OPTS -classpath cassandra-mesos-framework.jar io.mesosphere.mesos.frameworks.cassandra.framework.Main",
  "args": null,
  "user": null,
  "env": {
    "CASSANDRA_ZK_TIMEOUT_MS": "10000",
    "JAVA_OPTS": "-Xms256m -Xmx256m",
    "MESOS_AUTHENTICATE": "true",
    "CASSANDRA_RESOURCE_CPU_CORES": "0.1",
    "CASSANDRA_FAILOVER_TIMEOUT_SECONDS": "604800",
    "DEFAULT_SECRET": "secret",
    "CASSANDRA_BOOTSTRAP_GRACE_TIME_SECONDS": "120",
    "CASSANDRA_DEFAULT_DC": "DC1",
    "CASSANDRA_RESOURCE_MEM_MB": "768",
    "MESOS_ZK": "zk://zookeeper.service.consul:2181/mesos",
    "CASSANDRA_DATA_DIRECTORY": ".",
    "DEFAULT_PRINCIPAL": "mantl-install",
    "CASSANDRA_FRAMEWORK_MESOS_ROLE": "*",
    "CASSANDRA_CLUSTER_NAME": "dcos-test",
    "CASSANDRA_RESOURCE_DISK_MB": "16",
    "CASSANDRA_SEED_COUNT": "2",
    "CASSANDRA_ZK": "zk://zookeeper.service.consul:2181/cassandra-mesos/dcos-test",
    "CASSANDRA_NODE_COUNT": "3",
    "CASSANDRA_DEFAULT_RACK": "RAC1",
    "CASSANDRA_HEALTH_CHECK_INTERVAL_SECONDS": "60"
  },
  "instances": 1,
  "cpus": 0.5,
  "mem": 512,
  "disk": 0,
  "executor": "",
  "constraints": [],
  "uris": [
    "https://downloads.mesosphere.io/cassandra-mesos/artifacts/0.2.0-1/cassandra-mesos-0.2.0-1.tar.gz",
    "https://downloads.mesosphere.io/java/jre-7u76-linux-x64.tar.gz"
  ],
  "storeUrls": [],
  "ports": [
    0
  ],
  "requirePorts": false,
  "backoffFactor": 0,
  "container": null,
  "healthChecks": [
    {
      "path": "/health/cluster",
      "protocol": "HTTP",
      "portIndex": 0,
      "command": null,
      "gracePeriodSeconds": 120,
      "intervalSeconds": 15,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 0,
      "ignoreHttp1xx": false
    },
    {
      "path": "/health/process",
      "protocol": "HTTP",
      "portIndex": 0,
      "command": null,
      "gracePeriodSeconds": 120,
      "intervalSeconds": 30,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ],
  "dependencies": [],
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  },
  "labels": {
    "MANTL_PACKAGE_NAME": "cassandra",
    "MANTL_PACKAGE_IS_FRAMEWORK": "true",
    "DCOS_PACKAGE_FRAMEWORK_NAME": "cassandra.dcos-test",
    "MANTL_PACKAGE_FRAMEWORK_NAME": "cassandra.dcos-test",
    "MANTL_PACKAGE_INDEX": "1",
    "MANTL_PACKAGE_VERSION": "0.2.0-1"
  },
  "acceptedResourceRoles": null,
  "version": "2015-09-17T22:19:24.576Z",
  "tasks": [],
  "deployments": [
    {
      "id": "dd113528-388c-4438-a524-9eba45aa2908"
    }
  ],
  "tasksStaged": 0,
  "tasksRunning": 0,
  "tasksHealthy": 0,
  "tasksUnhealthy": 0,
  "backoffSeconds": 0,
  "maxLaunchDelaySeconds": 3600
}
```

### DELETE /1/installs

`DELETE /1/installs`: post a JSON representation of package specific uninstall options.

``` shell
curl -X DELETE -d "{\"name\": \"cassandra\"}" http://mantl-control-01/api/1/installs
```

## Comparison to Other Software

Mantl API leverages the [Mesosphere DCOS package repository](https://github.com/mesosphere/universe) and provides capabilities similar to the [`package`](https://docs.mesosphere.com/using/cli/packagesyntax/) command in the [DCOS CLI](https://github.com/mesosphere/dcos-cli). The goal is to provide a simple, API-driven way to install and uninstall pre-built packages on Mantl clusters. In the future, mantl-api will contain additional functionality for maintaining and operating Mantl clusters.

## Future Enhancement Ideas
1. Discover running packages (in progress) so that they can automatically be added to UI when applicable.
2. Operational tasks. Ability to see and manage Mesos frameworks, Marathon tasks, health checks, logs, etc.
3. Addons / Optional components. Turn on and off optional components.
4. Cluster management. Scale cluster up and down.
5. Other ideas?

## Issues
1. Dependency on Mesosphere repository
   
   Using the Mesosphere repository as the base repository is causing confusion &mdash; especially with package versions. In the next version of Mantl API, we should consider using Mant Universe as the only repository. It will have to be updated to include all package definitions. Repository layering would still be supported for users to create their own customized package configurations. **Feedback needed**.
2. Package schema is complicated.
   
   This is a particular challenge since there is currently no real standard on how frameworks are configured. Each framework is free to use it's own configuration method (args, env vars, config files, etc.) and naming conventions. At this point, it really takes someone with deep knowledge of a framework to create a package.
   
   We should consider ideas to simplify the existing packaging structure. By not relying on the Mesosphere repository (see 1. above), we would have more flexibility in the packaging format.
3. Development Workflow
   
   The workflow for developing new packages to include in the repository is a little too difficult right now. It requires running Mantl API locally, a repository directory structure, and access to a running Mantl cluster. The latter can be especially problematic if you are working with a remote cluster that has ssl, authentication, and firewall rules enabled. We need a simpler way to test a package definition against a cluster.

**Comment by ryane** [comment]
for review @PeterLamar @cdmitri @stevendborrelli @corebug

**Comment by stevendborrelli** [comment]
Adding @pinireznik.

**Comment by peterlamar** [comment]
Adding @bhramasw
